
#Questions

#1 Get all the questions
GET http://localhost:5000/kodehack/question
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ODBmNDYyYi0zNjg5LTRmZjctYWMzMS1jMjdhZmQ3MzBlY2QiLCJ1c2VybmFtZSI6IktldmluIE1hbG9tYmEiLCJlbWFpbCI6ImtldmlubWFsb21iYUBnbWFpbC5jb20iLCJ0aW1lQ3JlYXRlZCI6IjIwMjMtMDMtMjJUMDA6MDA6MDAuMDAwWiIsImlzX2FkbWluIjpmYWxzZSwiaXNfZGVsZXRlZCI6ZmFsc2UsIndlbGNvbWVfc2VudCI6dHJ1ZSwiZm9yZ290X3NlbnQiOmZhbHNlLCJpYXQiOjE2Nzk0Njk3NjAsImV4cCI6MTY3OTQ3MzM2MH0.MXs9iiotg4e7fxvPrpbuJQR1nuvV5-IGW0GQVQ_AJkw
###

#2 Ask a question
POST http://localhost:5000/kodehack/question
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ODBmNDYyYi0zNjg5LTRmZjctYWMzMS1jMjdhZmQ3MzBlY2QiLCJ1c2VybmFtZSI6IktldmluIE1hbG9tYmEiLCJlbWFpbCI6ImtldmlubWFsb21iYUBnbWFpbC5jb20iLCJ0aW1lQ3JlYXRlZCI6IjIwMjMtMDMtMjJUMDA6MDA6MDAuMDAwWiIsImlzX2FkbWluIjpmYWxzZSwiaXNfZGVsZXRlZCI6ZmFsc2UsIndlbGNvbWVfc2VudCI6dHJ1ZSwiZm9yZ290X3NlbnQiOmZhbHNlLCJpYXQiOjE2Nzk0Njk3NjAsImV4cCI6MTY3OTQ3MzM2MH0.MXs9iiotg4e7fxvPrpbuJQR1nuvV5-IGW0GQVQ_AJkw
Content-Type: application/json


{

    "title": "Hi",
    "category": "ENG",
    "question": "Hi there",
    "timeCreated": "2015-12-13T00:00:00.000Z",
    "userId": "1",
    
}

###

#3 Get one question
GET  http://localhost:5000/kodehack/question/2
###

#4 Update question
PUT http://localhost:5000/kodehack/question
Content-Type: application/json

{
"title":"Update question",
"category":"JS updated",
"question":"How to use alert, prompt",
"timeCreated":"12-12-12",
"userId":null
}

###

#5 Delete question
DELETE  http://localhost:5000/kodehack/question/26401964-9545-47c3-8358-a841ef96d3c3

###

# Answers
#1 Get all the answers
GET http://localhost:5000/kodehack/answer
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ODBmNDYyYi0zNjg5LTRmZjctYWMzMS1jMjdhZmQ3MzBlY2QiLCJ1c2VybmFtZSI6IktldmluIE1hbG9tYmEiLCJlbWFpbCI6ImtldmlubWFsb21iYUBnbWFpbC5jb20iLCJ0aW1lQ3JlYXRlZCI6IjIwMjMtMDMtMjJUMDA6MDA6MDAuMDAwWiIsImlzX2FkbWluIjpmYWxzZSwiaXNfZGVsZXRlZCI6ZmFsc2UsIndlbGNvbWVfc2VudCI6dHJ1ZSwiZm9yZ290X3NlbnQiOmZhbHNlLCJpYXQiOjE2Nzk0Njk3NjAsImV4cCI6MTY3OTQ3MzM2MH0.MXs9iiotg4e7fxvPrpbuJQR1nuvV5-IGW0GQVQ_AJkw
###


#2 Get one Answer
GET  http://localhost:5000/kodehack/answer/1

###


#3 Answer a question
POST http://localhost:5000/kodehack/answer
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ODBmNDYyYi0zNjg5LTRmZjctYWMzMS1jMjdhZmQ3MzBlY2QiLCJ1c2VybmFtZSI6IktldmluIE1hbG9tYmEiLCJlbWFpbCI6ImtldmlubWFsb21iYUBnbWFpbC5jb20iLCJ0aW1lQ3JlYXRlZCI6IjIwMjMtMDMtMjJUMDA6MDA6MDAuMDAwWiIsImlzX2FkbWluIjpmYWxzZSwiaXNfZGVsZXRlZCI6ZmFsc2UsIndlbGNvbWVfc2VudCI6dHJ1ZSwiZm9yZ290X3NlbnQiOmZhbHNlLCJpYXQiOjE2Nzk0Njk3NjAsImV4cCI6MTY3OTQ3MzM2MH0.MXs9iiotg4e7fxvPrpbuJQR1nuvV5-IGW0GQVQ_AJkw

{
    "answer": "Bonjour",
    "timeCreated": "2023-12-12T00:00:00.000Z",
    "userId": "1",
    "questionId": "1",
    "is_checked": false
   
}


###
#4 Delete an answer
DELETE  http://localhost:5000/kodehack/answer/1

###




# Comments
#1 Get all the comments
GET http://localhost:5000/kodehack/comments
###

#2 Delete comments
DELETE  http://localhost:5000/kodehack/comments/1
###



# users
# 1.0 get all users
GET http://localhost:5000/kodehack/users
###
# 2.0 Add users






#Signup
POST http://localhost:5000/kodehack/auth/register

###
#Login
POST http://localhost:5000/kodehack/auth/login
Content-Type: application/json

{
    "email": "willymalomba@gmail.com",
    "password": "KMalomba;75!"
}

###
#test authorization
GET http://localhost:5000/kodehack/auth/home
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNTI5NzIxMS05YmFhLTQzYTctODYzNy1lMWZkOTRiYzc5MTgiLCJlbWFpbCI6Im1hbG9tYmFAZ21haWwuY29tIiwidGltZUNyZWF0ZWQiOiIyMDIzLTAzLTIxVDAwOjAwOjAwLjAwMFoiLCJpc19hZG1pbiI6ZmFsc2UsImlzX2RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE2NzkzOTY5NzUsImV4cCI6MTY3OTQwMDU3NX0.j0IFk6Rkyjdgwc6ew_QVfygYHCULQnbiG71ZUgelUE03173287f-9917-4fa5-aa53-4d48cc7c667b